spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soomgo
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver

flyway:
  locations: classpath:db/migration
  baseline-on-migrate: true


#RDS
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@your-rds-endpoint:1521:your-db-name
#    username: your-username
#    password: your-password
#    driver-class-name: oracle.jdbc.OracleDriver
#
#flyway:
#  locations: classpath:db/migration
#  baseline-on-migrate: true
